### ISSUE TITLE
aliasFile

### ISSUE THREAD

**Issue by raelinamarie** [jbuehl/ha#18]
While running bash/test I'm getting this error message. 

CherryPy Checker:
'/home/raelina/ha/static/css' (root + dir) is not an existing filesystem path.
section: [/css]
root: '/home/raelina/ha/static'
dir: 'css'

CherryPy Checker:
'/home/raelina/ha/static/js' (root + dir) is not an existing filesystem path.
section: [/js]
root: '/home/raelina/ha/static'
dir: 'js'

CherryPy Checker:
'/home/raelina/ha/static/images' (root + dir) is not an existing filesystem path.
section: [/images]
root: '/home/raelina/ha/static'
dir: 'images'

So it looks like aliasFile in haTest.py is what is generating the incorrect file path, and I'm not sure how to change it.

**Comment by jbuehl** [comment]
It’s not related to the alias file.  The subfolders under ha/static aren’t on the server.  Are they on your laptop?  They should be copied to the server when you do a bin/deploy.

**Comment by raelinamarie** [comment]
OH. Okay. So in bin/deploy the script is supposed to send the files to the server? The files are on my laptop, but how do I get those to the server?
